### PR TITLE
Feature/information hash

### PR DESCRIPTION
**Pull request by TylerRockwell**
Hey Rick, thanks for putting the base of this gem together. SB's given me some time to work on it, so
I'll be sending quite a few PR's your way. Here's the first. Updated README will be in the next one.
#### What Changed
- Added an information hash, so you're not limited to one note per test.
- Changed the `@skip` variable from an integer to a boolean
- Made general readability changes to the code.

### CODE REVIEW

**Comment by RickCarlino** [comment]
Hey @TylerRockwell thanks for the PR.

Regarding the change of `@skip` as a flag rather than a counter:

Does this cause any issue when there are multiple skips in a test? As you could have probably seen from the comments I left, I was not a big fan of using integers, but it came from some edge cases. Unfortunately, memory is not serving me well as to what those edge cases were.

It looks like you changed the tests and they work fine, so I'm OK with it if you are (really wish I documented the reason for using skip counter in the first place...)

@albaer You did a PR related to multiple skips a while back- do you have any recollection of that edge case?

Looks good otherwise. Will merge pending further comments from @TylerRockwell or @albaer

**Comment by TylerRockwell** [comment]
@RickCarlino Not that I can see. The test for multiple skips passes, and I've tested it manually by installing SmarfDoc into another app. I haven't seen any issues from it. I'm sure you had a reason for using integers, but thus far, I haven't had issues with it.

**Comment by RickCarlino** [comment]
Ok, cool.

Do you think you could bump the version from `0.0.1` to `1.0.0`. I think this is "major" enough to warrant a version bump. I can publish this to rubygems.org when I get to my usual workstation (out and about at the moment).

**Comment by TylerRockwell** [comment]
Done.

**Comment by RickCarlino** [comment]
:tada: :confetti_ball: Thanks!

**Comment by albaer** [comment]
Yay! I'm a little late to the party, but the edge case I worked on was skipping multiple tests in a row, and that still works so I think we're good.

**Comment by RickCarlino** [comment]
Ok folks- it's up on RubyGems.org.

**Pull request merged**
